FROM docker:28-cli@sha256:625d9431a9f54c5a2bc90f24f0e1c3d55b1349fd857dd85035f98c2c9acbdd4d

RUN apk add --no-cache curl bash \
    && curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | bash -s -- -b /usr/local/bin

COPY actrc /root/.config/act/actrc

ENTRYPOINT ["tail", "-f", "/dev/null"]
